
# tasks file for apache2

- name: install apache2
  become: yes
  apt :
       name : "apache2"
       update_cache : yes
       state: latest

- name: "Installation of certbot"
  apt:
    name={{ item }}
    state=latest
  loop :
    -  certbot
    -  python-certbot-apache

- name: enabled mod_rewrite
  apache2_module :
    name : rewrite
    state: present
  notify:
    - restart apache2
