# tasks file for common

- name: Update the apt package index
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Set authorized key taken from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


- name: "Installation des logiciels communs"
  apt:
    name={{ item }}
    state=latest
  loop :
    -  vim
    -  git
    -  tree
    -  htop
    -  curl
    -  emacs
    -  net-tools
    -  lsb-release
    -  apt-transport-https
    -  ca-certificates
    -  python3
    -  sudo
    -  make
    -  unzip
